var ru = {

	add: "Добавить",
	back: "Назад",
	emailSent: "Письмо отправлено",
  signIn: "Личный Кабинет",
  signin: "Войти в Личный Кабинет",
  signOut: "Выйти",
  signout: "Выход",
  signUp: "Зарегистрироваться",
  OR: "или",
  forgotPassword: "Забыли пароль?",
  forgotPasswordTitle: "Смена пароля",
  emailAddress: "Электронный адрес",
  emailResetLink: "Отправить ссылку",
  dontHaveAnAccount: "Еще не зарегистрированы?",
  resetYourPassword: "Изменение пароля",
  cancelResetYourPassword: "Отменить изменение пароля",
  updateYourPassword: "Установить пароль",
  promptLoginServices: "Для входа в Личный Кабинет Вы можете использовать свои учетные записи на:",
  promptSignIn: "Введите Ваш электронный адрес и пароль для входа в Личный Кабинет.",
  promptForgotPassword: "Пожалуйста, введите Ваш электронный адрес, и мы отправим на него ссылку на страницу изменения пароля.",
  promptResetPassword: "Чтобы изменить пароль для входа в Личный Кабинет, пожалуйста, введите новый пароль.",
  promptCancelResetPassword: "Не хотите изменять пароль?",
  password: "Пароль",
  newPassword: "Новый пароль",
  usernameOrEmail: "Имя пользователя или электронный адрес",
  email: "Электронный адрес",
  ifYouAlreadyHaveAnAccount: "Уже зарегистрированы?",
  signUpWithYourEmailAddress: "Зарегистрироваться с помощью Вашего электронного адреса",
  username: "Имя пользователя",
  optional: "Не обязательно",
  signupCode: "Код регистрации",
  signupCodeText: "Пожалуйста, введите код регистрации:",
  clickAgree: "Зарегистрировавшись, Вы принимаете",
  privacyPolicy: "Политика конфиденциальности",
  terms: "Условия использования",
  sign: "Войти",
  alreadyLoggedIn: "Вы уже вошли в систему",
  gotoAccount: "Зайти в Личный Кабинет",
  signOutFromAccount: "Выйти из системы",
  configure: "Настройка",
  "with": "с помощью",
  createAccount: "Регистрация",
  and: "и",
  cancel: "Отмена",
  error: {
		minChar: "Пароль должен содержать минимум 7 символов.",
		pwOneLetter: "Пароль должен содержать минимум одну букву.",
		pwOneDigit: "Пароль должен содержать минимум одну цифру.",
		usernameRequired: "Пожалуйста, укажите имя пользователя.",
		emailRequired: "Пожалуйста, укажите Ваш электронный адрес.",
		signupCodeRequired: "Пожалуйста, введите код регистрации.",
		signupCodeIncorrect: "Не верный код регистрации.",
		signInRequired: "Пожалуйста, войдите в систему.",
		usernameIsEmail: "Имя пользователя не может быть электронным адресом.",
		fillComment: "Пожалуйста, заполните комментарий.",
		fillScore: "Пожалуйста, оцените пользователя от 1 (плохо) до 5 (отлично) звезд.",
		orderNotFound: "Заказ не найден.",
		userNotFound: "Пользователь не найден.",
		reviewExists: "Вы уже оставляли отзыв об этом пользователе.",
		"Please confirm your new password": "Пожалуйста, подтвердите свой новый пароль.",
		"Please provide your new password": "Пожалуйста, введите свой новый пароль.",
		accounts: {
			"You've been logged out by the server. Please login again.": "Вы были отключены сервером. Пожалуйста, зайдите еще раз.",
			"Your session has expired. Please login again.": "Ваша сессия истекла. Пожалуйста зайдите еще раз.",
			"User validation failed": "Пользователь не прошел проверку.",
			"Email already exists": "Такой электронный адрес уже зарегистрирован.",
			"Username already exists": "Такое имя пользователя уже используется.",
			"Email doesn't match the criteria.": "Электронный адрес не соответствует формату.",
			"Match failed": "Пожалуйста, введите свой старый пароль.",
			"User not found": "Пользователь не найден.",
			"User has no password set": "У пользователя не установлен пароль.",
			"Incorrect password": "Неверный пароль.",
			"Must be logged in": "Вы должны войти в систему.",
			"Invalid verifier": "Неверный код подтверждения.",
			"Token expired": "Токен просрочен.",
			"Token has invalid email address": "Токен имеет неверный электронный адрес.",
			"Verify email link expired": "Время действия ссылки на подтверждение электронного адреса истекло.",
			"Verify email link is for unknown address": "Ссылка на подтверждение для неизвестного электронного адреса.",
			"Need to set a username or email": "Вы должны указать имя пользователя или электронный адрес.",
			"Signups forbidden": "В данный момент регистрация запрещена.",
		}
  },
  "Match failed": "Совпадений не найдено",
  "Incorrect password": "Неверный пароль",
  "User not found": "Пользователь не найден",
  "Validation Errors": "Ошибки валидации",
  "Required Field": "Обязательное поле",
  "Minimum Required Length": "Минимально допустимая длина",
  "Maximum Allowed Length": "Максимально допустимая длина",
  "Do you really want to delete this photo from your pofile?": "Вы действительно хотите удалить эту фотографию из Вашей анкеты?",



  "Site Name": "Studlab",
  "Exit": "Выход",
  "Access denied": "Пожалуйста, войдите в систему...",
  "Our Contacts": "Наши контакты",
  "Welcome": "Добро пожаловать!",
  "Homepage": "Главная страница",
  "Home": "Главная",
  "Profile": "Анкета",
  "My Profile": "Моя анкета",
  "Author Profile": "Анкета автора",
  "Customer Profile": "Анкета заказчика",
  "Dashboard": "Моя страница",
  "Edit Profile": "Редактировать анкету",
  "User": "Пользователь",
  "Users": "Пользователи",
  "Orders": "Заказы",
  "orders": "заказы",
  "Order": "Заказ",
  "order": "заказ",
  "New": "Новый",
  "Comments": "Комментарии",
  "Edit Order": "Редактирование заказа",
  "New Order": "Новый заказ",
  "Authors Rating": "Рейтинг авторов",
  "Reviews": "Отзывы",
  "Rating": "Рейтинг",
  "Customer Account": "Личный кабинет заказчика",
  "Author Account": "Личный кабинет автора",
  "Applications": "Приложения",
  "Information": "Информация",
  "Privacy": "Конфиденциальность",
  "Social": "Мы на связи",
  "Slogan": "Первая Украинская Биржа Рефератов",
  "Mission 1": "Прямое общение между студентом и автором",
  "Mission 2": "Гарантия качества и сроков исполнения заказа",
  "Mission 3": "Депозитная система оплаты",
  "Leave a comment": "Оставить комментарий",
  "Leave a review": "Оставить отзыв",
  "Send": "Отправить",
  "Order Comments": "Комментарии к заказу",
  "Comment Prompt": "Чтобы оставить комментарий, пожалуйста, войдите в систему.",
  "No comments yet": "Нет комментариев",
  "Notifications": "Уведомления",
  "No notifications": "Нет непрочитанных уведомлений",
  "leave a comment": "оставил(а) комментарий",
  "leave a review": "оставил(а) отзыв",
  "create a new order": "создал(а) новый заказ",
  "Clear Notifications": "Стереть все уведомления",
  "Total Notifications": "Непрочитанных уведомлений",
  "Statistics": "Статистика",
  "Learn more...": "Узнать больше...",
  "Theme": "Тема",
  "Science": "Предмет",
  "Select science": "Выберите предмет",
  "Language": "Язык",
  "Select language": "Выберите язык",
  "Input or select": "Введите название или выберите из списка",
  "Selected sciences": "Выбранные предметы",
  "Selected languages": "Выбранные языки",
  "Science filter": "Фильтр по предметам",
  "Customer": "Заказчик",
  "Customers": "Заказчики",
  "Author": "Автор",
  "Authors": "Авторы",
  "Offers": "Ставки",
  "Details": "Детали",
  "offers": "ставок",
  "comments": "комментариев",
  "Private Info": "Личные данные",
  "Professional Info": "Профессиональные данные",
  "Photo": "Фото",
  "Upload Photo": "Загрузить фото",
  "Delete Photo": "Удалить фото",
  "Name": "Имя",
  "Phone": "Телефон",
  "Birthday": "День рождения",
  "Location": "Местоположение",
  "Degree": "Образование",
  "Academic Title": "Степень",
  "University": "ВУЗ",
  "Post": "Должность",
  "Sciences": "Предметы",
  "Languages": "Языки",
  "Biography": "О себе",
  "Feed": "Лента",
  "works": "Работы",
  "Works": "Готовые работы",
  "Hide sidebar": "Закрыть панель",
  "Show sidebar": "Открыть панель",
  "No orders yet": "Пока нет ни одного заказа",
  "No reviews yet": "Пока нет ни одного отзыва",
  "No works yet": "Пока нет ни одной готовой работы",
  "Not specified": "Не указано",
  "Vote": "Проголосовать",
  "Bad": "Плохо",
  "Excellent": "Отлично",
  "Total": "Всего",
  "total": "всего",
  "stars": "звезд",
  "More": "Другие...",
  "Less": "Свернуть...",
  "Settings": "Настройки",
  "Security": "Безопасность",
  "Change Password": "Смена пароля",
  "Old Password": "Старый пароль",
  "New Password": "Новый пароль",
  "Confirm New Password": "Новый пароль (еще раз)",
  "About author": "Об авторе",
  "About customer": "О заказчике",
  "About me": "Обо мне",
  "Online": "Сейчас на сайте",
  "Offline": "Нет на сайте",
  "Last logon": "Последний визит",
  "No content": "Нет данных",
  "No path": "Такой страницы не существует",
  "Error": "Ошибка",
  "Country": "Страна",
  "City": "Город",
  "Edit": "Редактировать",
  "Save": "Сохранить",
  "Cancel": "Отмена",
  "Not found": "Ничего не найдено",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",

  "Status": "Статус",
  status: {
  	"new": "Новый",
  	"process": "В работе",
  	"done": "Сдан",
  	"warranty": "На гарантии",
  	"closed": "Закрыт",
  },
  ordersByStatus: {
  	"new": "Новые",
  	"process": "В работе",
  	"done": "Сданные",
  	"warranty": "На гарантии",
  	"closed": "Закрытые",
  	"add": "Новый заказ",
  },

};


T9n.map("ru", ru);


t9nLists['ru'] = {

	languages: {
		'Ukrainian': 'Украинский',
		'Russian': 'Русский',
		'Belarusian': 'Беларусский',
		'Georgian': 'Грузинский',
		'Kazakh': 'Казахский',
		'English': 'Английский',
		'French': 'Французский',
		'Spanish': 'Испанский',
		'German': 'Немецкий',
		'Italian': 'Итальянский'
	},

	countries: {
		'Ukraine': 'Украина',
		'Russia': 'Россия',
		'Belarus': 'Беларусь',
		'Georgia': 'Грузия',
		'Kazakhstan': 'Казахстан'
	},

	degrees: {
		'Higher': 'Высшее',
		'Incomplete Higher': 'Неоконченное высшее',
		'Secondary Special': 'Среднее специальное',
		'Secondary': 'Среднее'
	},

	academicTitles: {
		'Professor': 'Профессор',
		'Master': 'Магистр',
		'Doctor of Sciences': 'Доктор наук',
		'Candidate to Doctor of Sciences': 'Кандидат наук'
	},

	scienceChapters: {
		'Economic Sciences': 'Экономические',
		'Jurisprudence Sciences': 'Юридические',
		'Exact Sciences': 'Точные',
		'Human Sciences': 'Гуманитарные',
	},

	sciences: {

		'Economic Sciences': '',
			'Crisis management': 'Антикризисное управление',
			'Audit': 'Аудит',
			'Banking': 'Банковское дело',
			'Business Planning': 'Бизнес-планирование',
			'Exchange trade': 'Биржевая торговля',
			'Accounting': 'Бухгалтерский учет',
			'Budget system': 'Бюджетная система',
			'Foreign economic activity': 'Внешнеэкономическая деятельность',
			'Geopolitics': 'Геополитика',
			'State and municipal management': 'Государственное и муниципальное управление',
			'State regulation of economy': 'Государственное регулирование экономики',
			'State financial control': 'Государственный финансовый контроль',
			'Money and credit': 'Деньги и кредит',
			'Investments': 'Инвестиции',
			'Innovations': 'Инновации',
			'Institutional Economics': 'Институциональная экономика',
			'Commodity market infrastructure': 'Инфраструктура товарного рынка',
			'History of Economic Thought': 'История экономических учений',
			'Controlling': 'Контроллинг',
			'Control and revision': 'Контроль и ревизия',
			'Corporate governance': 'Корпоративное управление',
			'Leasing': 'Лизинг',
			'Logistics': 'Логистика',
			'Macroeconomics': 'Макроэкономика',
			'Marketing': 'Маркетинг',
			'International relations': 'Международные отношения',
			'International economic relations': 'Международные экономические отношения',
			'Management': 'Менеджмент',
			'Microeconomics': 'Микроэкономика',
			'Global economy': 'Мировая экономика',
			'Taxes and taxation': 'Налоги и налогообложение',
			'Organizational Behavior': 'Организационное поведение',
			'Organization of production': 'Организация производства',
			'Labour Organization': 'Организация труда',
			'Sectoral Economics': 'Отраслевая экономика',
			'Assessment and evaluation activities': 'Оценка и оценочная деятельность',
			'Planning and control of the enterprise': 'Планирование и контроль на предприятии',
			'Entrepreneurship': 'Предпринимательство',
			'Distribution of productive forces': 'Размещение производительных сил (РПС)',
			'Regional and national economy': 'Региональная и национальная экономика',
			'Business Process Reengineering': 'Реинжиниринг бизнес-процессов',
			'Advertising': 'Реклама',
			'Risk Management': 'Риск-менеджмент',
			'Financial services market': 'Рынок финансовых услуг',
			'Securities market': 'Рынок ценных бумаг',
			'Public Relations (PR)': 'Связи с общественностью (PR)',
			'Systems Technologies': 'Системы технологий',
			'Strategic Management': 'Стратегическое управление',
			'Insurance': 'Страхование',
			'Customs business': 'Таможенное дело',
			'Organization Theory': 'Теория организации',
			'Trading Business': 'Торговое дело',
			'Cost Management': 'Управление затратами',
			'Quality control': 'Управление качеством',
			'Management of competitiveness': 'Управление конкурентоспособностью',
			'HR Management': 'Управление персоналом',
			'Project Management': 'Управление проектами',
			'Management decisions': 'Управленческие решения',
			'Financial Planning and Forecasting': 'Финансовое планирование и прогнозирование',
			'Financial management': 'Финансовый менеджмент',
			'Finance': 'Финансы',
			'Finance companies': 'Финансы предприятий',
			'Pricing': 'Ценообразование',
			'Business Economics': 'Экономика предприятий',
			'Environmental Economics': 'Экономика природопользования',
			'Labour Economics': 'Экономика труда',
			'Economic theory': 'Экономическая теория',
			'Economic analysis': 'Экономический анализ',

		'Jurisprudence Sciences': '',
			'Agrarian law': 'Аграрное право',
			'Advocacy': 'Адвокатура',
			'Administrative law': 'Административное право',
			'The administrative process': 'Административный процесс',
			'Banking law': 'Банковское право',
			'Civil process': 'Гражданский процесс',
			'Civil and commercial law of foreign countries': 'Гражданское и торговое право зарубежных стран',
			'Civil law': 'Гражданское право',
			'Diplomatic and consular service': 'Дипломатическая и консульская служба',
			'European Union Law': 'Европейское право',
			'Housing law': 'Жилищное право',
			'Land law': 'Земельное право',
			'Suffrage': 'Избирательное право',
			'Investment Law': 'Инвестиционное право',
			'Information Law': 'Информационное право',
			'Executory process': 'Исполнительное производство',
			'History of State and Law': 'История государства и права',
			'History of political and legal studies': 'История политических и правовых учений',
			'Commercial law': 'Коммерческое право',
			'Constitutional law of foreign countries': 'Конституционное право зарубежных стран',
			'Constitutional law': 'Конституционное право',
			'Corporate right': 'Корпоративное право',
			'Criminalistics': 'Криминалистика',
			'Criminology': 'Криминология',
			'International public law': 'Международное публичное право',
			'Private international law': 'Международное частное право',
			'Municipal law': 'Муниципальное право',
			'Tax law': 'Налоговое право',
			'Notary': 'Нотариат',
			'Operatively-search activity': 'Оперативно-розыскная деятельность',
			'Intellectual property rights': 'Право интеллектуальной собственности',
			'Right to social security': 'Право социального обеспечения',
			'Jurisprudence': 'Правоведение',
			'Prosecutorial Supervision': 'Прокурорский надзор',
			'Professional Ethics for Lawyers': 'Профессиональная этика юриста',
			'Roman law': 'Римское право',
			'Law of domestic relations': 'Семейное право',
			'Comparative law': 'Сравнительное правоведение',
			'Insurance law': 'Страховое право',
			'Forensic medicine': 'Судебная медицина',
			'Judicial rhetoric': 'Судебная риторика',
			'Forensic examination': 'Судебная экспертиза',
			'Judicial and law enforcement authorities': 'Судебные и правоохранительные органы',
			'Customs law': 'Таможенное право',
			'Theory of State and Law': 'Теория государства и права',
			'Transport Law': 'Транспортное право',
			'Labor law': 'Трудовое право',
			'Criminal law': 'Уголовное право',
			'Penal law': 'Уголовно-исполнительное право',
			'Criminal process': 'Уголовный процесс',
			'Financial law': 'Финансовое право',
			'Economic law': 'Хозяйственное право',
			'Economic process': 'Хозяйственный процесс',
			'Environmental Law': 'Экологическое право',
			'Legal Anthropology': 'Юридическая антропология',
			'Legal Conflict': 'Юридическая конфликтология',
			'Legal psychology': 'Юридическая психология',
			'Legal technics': 'Юридическая техника',

		'Exact Sciences': '',
			'Aviation and Transportation': 'Авиакосмический транспорт',
			'Aviation equipment': 'Авиационная техника',
			'Cars, motorcycles, bicycles and agricultural transport': 'Авто-, мото-, вело- и сельскохозяйственный транспорт',
			'Automobiles and tractors': 'Автомобильная и тракторная техника',
			'Automation': 'Автоматизация',
			'Agrochemistry and Soil': 'Агрохимия и агропочвоведение',
			'Acoustics and sound technicians': 'Акустика и звукотехника',
			'Analytical chemistry': 'Аналитическая химия',
			'Antenna-feeder devices': 'Антенно-фидерные устройства',
			'Architecture': 'Архитектура',
			'Astronomy and Astrophysics': 'Астрономия и астрофизика',
			'Databases': 'Базы данных',
			'Biofuels, bioenergy': 'Биотопливо, биоэнергетика',
			'Ventilation and air conditioning': 'Вентиляция и кондиционирование',
			'Interchangeability, standardization and technical measurements': 'Взаимозаменяемость, стандартизация и технические измерения (ВСТИ)',
			'Water transport Navigation': 'Водный транспорт Судовождение',
			'Water supply and sanitation': 'Водоснабжение и водоотведение',
			'Fiber-optic transmission systems': 'Волоконно-оптические системы передачи',
			'High-processing methods': 'Высокоэнергетические методы обработки',
			'Higher mathematics': 'Высшая математика',
			'Computational Mathematics': 'Вычислительная математика',
			'Computers, systems and networks': 'Вычислительные машины, системы и сети (ВМСС)',
			'Gas supply': 'Газоснабжение',
			'Geography': 'География',
			'Geodesy and Mine Surveying': 'Геодезия и маркшейдерия',
			'Geographic information technologies (GIS)': 'Геоинформационные технологии (ГИС)',
			'Geology': 'Геология',
			'Hydraulics and hydraulic': 'Гидравлика и гидропривод',
			'Hydraulic structures': 'Гидротехнические сооружения',
			'Mining': 'Горное дело',
			'Mining machinery and equipment': 'Горные машины и оборудование',
			'Town planning and town planning': 'Градостроительство и благоустройство городов',
			'Civil and industrial buildings': 'Гражданские и промышленные здания',
			'Goods Transportion Gruzovedenie': 'Грузопассажирские перевозки Грузоведение',
			'Internal combustion engines (ICE)': 'Двигатели внутреннего сгорания (ДВС)',
			'Machine parts and design principles': 'Детали машин и основы конструирования',
			'Design': 'Дизайн',
			'Discrete Mathematics': 'Дискретная математика',
			'Railway transport': 'Железнодорожный транспорт',
			'Livestock and fisheries': 'Животноводство и промыслы',
			'Agriculture': 'Земледелие',
			'Informatics': 'Информатика',
			'Information technology': 'Информационные технологии',
			'Artificial intelligence': 'Искусственный интеллект',
			'Stone cutting and jewelry making': 'Камнерезное и ювелирное дело',
			'Quantum physics and relativity': 'Квантовая физика и теория относительности',
			'Cybernetics': 'Кибернетика',
			'Compressor and pump equipment': 'Компрессорное и насосное оборудование',
			'Computer graphics': 'Компьютерная графика',
			'Computer Simulation': 'Компьютерное моделирование',
			'Design and production technology of CEA': 'Конструирование и технология производства РЭА',
			'Design and Technology Software': 'Конструкторско-технологическое обеспечение',
			'Test and Measurement and Automation': 'Контрольно-измерительные приборы и автоматика',
			'Corrosion': 'Коррозия',
			'Boiler systems': 'Котельные установки',
			'Crystal chemistry': 'Кристаллохимия',
			'Logistics': 'Логистика',
			'Mathematics': 'Математика',
			'Mathematical logic': 'Математическая логика',
			'Mathematical Physics': 'Математическая физика',
			'Mathematical methods and modeling': 'Математические методы и моделирование',
			'Materials Science': 'Материаловедение',
			'Mathematical methods': 'Математические методы',
			'Machines and devices': 'Машины и аппараты',
			'Machinery and equipment, oil and gas industry': 'Машины и оборудование нефтегазовой промышленности',
			'Reclamation': 'Мелиорация',
			'Metallurgy and heat treatment': 'Металловедение и термическая обработка',
			'Metal-cutting machines': 'Металлорежущие станки',
			'Metallurgy': 'Металлургия',
			'Metrology': 'Метрология',
			'Mechanics': 'Механика',
			'Microprocessor Systems (ICS)': 'Микропроцессорные системы (МПС)',
			'Mineralogy and Crystallography': 'Минералогия и кристаллография',
			'Installation, maintenance and repair of electrical equipment': 'Монтаж, эксплуатация и ремонт электрооборудования',
			'Pump and compressor station pipelines': 'Насосные и компрессорные станции магистральных трубопроводов',
			'Descriptive Geometry and Engineering Graphics': 'Начертательная геометрия и инженерная графика',
			'Oil and gas': 'Нефтегазовое дело',
			'Metal Forming': 'Обработка металлов давлением',
			'Signal Processing': 'Обработка сигналов',
			'General technology and theoretical bases of food production': 'Общая технология и теоретические основы пищевых производств',
			'Operating Systems': 'Операционные системы',
			'Optics': 'Оптика',
			'Optoelectronics': 'Оптоэлектроника',
			'Bases and foundations': 'Основания и фундаменты',
			'Transients': 'Переходные процессы',
			'Pneumatics and pneumatic': 'Пневматика и пневмопривод',
			'Handling machinery': 'Подъемно-транспортные машины',
			'Processes and equipment for food production': 'Процессы и аппараты пищевых производств',
			'Processes and devices of chemical technology': 'Процессы и аппараты химической технологии',
			'Programming': 'Программирование',
			'Radiolocation': 'Радиолокация',
			'Radio communication': 'Радиосвязь',
			'Radiotechnics': 'Радиотехника',
			'Crop': 'Растениеводство',
			'Calculation and design of gas and oil pipelines': 'Расчет и проектирование газонефтепроводов',
			'Metal cutting and tool': 'Резание металлов и инструмент',
			'Relay protection and automation of EC': 'Релейная защита и автоматизация ЭС',
			'CAD': 'САПР',
			'E rural households on': 'Сельское хозяйство',
			'Communication Networks and Switching Systems': 'Сети связи и системы коммутации',
			'Computer Networks': 'Сети ЭВМ',
			'Power Electronics': 'Силовая электроника',
			'System analysis': 'Системный анализ',
			'Estimate work': 'Сметное дело',
			'Strength of materials': 'Сопротивление материалов',
			'Statistics': 'Статистика',
			'Structural mechanics': 'Строительная механика',
			'Building construction': 'Строительные конструкции',
			'Construction machinery and equipment': 'Строительные машины и оборудование',
			'Construction, operation and maintenance of pipeline systems': 'Строительство, эксплуатация и ремонт трубопроводных систем',
			'Shipbuilding': 'Судостроение',
			'Circuitry': 'Схемотехника',
			'Telecommunications': 'Телекоммуникации',
			'Theoretical Mechanics': 'Теоретическая механика',
			'Theoretical Foundations of management automation': 'Теоретические основы автоматизации управления',
			'Theoretical Foundations of Electrical Engineering (TBE)': 'Теоретические основы электротехники (ТОЭ)',
			'Theory of Automatic Control (TAU)': 'Теория автоматического управления (ТАУ)',
			'Automata Theory': 'Теория автоматов',
			'Theory of algorithms': 'Теория алгоритмов',
			'Probability theory and mathematical statistics': 'Теория вероятностей и математическая статистика',
			'Theory and modeling of traffic flows and networks': 'Теория и моделирование транспортных потоков и сетей',
			'Information theory and error-correcting codes': 'Теория информации и корректирующие коды',
			'Theory of Information Systems': 'Теория информационных систем',
			'Theory of oscillations': 'Теория колебаний',
			'Theory of Mechanisms and Machines (TMM)': 'Теория механизмов и машин (ТММ)',
			'Reliability theory': 'Теория надежности',
			'Decision theory (TPD)': 'Теория принятия решений (ТПР)',
			'The theory of stochastic processes': 'Теория случайных процессов',
			'The thermal part of TPP, NPP, TPP': 'Тепловая часть ТЭС, АЭС, ТЭЦ',
			'Heat pumps': 'Тепловые насосы',
			'Heat networks': 'Тепловые сети',
			'Heat exchangers': 'Теплообменные аппараты',
			'Heat supply': 'Теплоснабжение',
			'Thermotechnics': 'Теплотехника',
			'Thermal Engineering Batteries heat': 'Теплоэнергетика Аккумуляторы тепловой энергии',
			'Thermodynamics, molecular and statistical physics': 'Термодинамика, молекулярная и статистическая физика',
			'Thermoelectric energy': 'Термоэлектрическая энергетика',
			'High Voltage Equipment': 'Техника высоких напряжений',
			'Technical Thermodynamics': 'Техническая термодинамика',
			'Technical operation of vehicles': 'Техническая эксплуатация автомобилей',
			'Means of automation (TCA)': 'Технические средства автоматизации (ТСА)',
			'Technological Equipment of Food Production': 'Технологическое оборудование пищевых производств',
			'Technology of construction of buildings': 'Технология возведения зданий',
			'Technology and organization of transport': 'Технология и организация перевозок',
			'Engineering Technology': 'Технология машиностроения',
			'Technology of Food Production': 'Технология пищевых производств',
			'Technology of construction processes': 'Технология строительных процессов',
			'Technology of textile materials': 'Технология текстильных материалов',
			'Commodity research': 'Товароведение',
			'Fuel and combustion theory': 'Топливо и теория горения',
			'Transport system and transport management': 'Транспортная система и управление на транспорте',
			'Transportation waterworks': 'Транспортные гидротехнические сооружения',
			'Tribology and Tribotechnics': 'Трибология и триботехника',
			'Pipeline transport Mining of hydrocarbon resources': 'Трубопроводный транспорт Магистральный транспорт углеводородных ресурсов',
			'Project Management': 'Управление проектами',
			'Quality control': 'Управление качеством',
			'Physics': 'Физика',
			'Plasma Physics': 'Физика плазмы',
			'Physics rock formations arrays': 'Физика пород, пластов, массивов',
			'Solid State Physics': 'Физика твердого тела',
			'Physical and Colloid Chemistry': 'Физическая и коллоидная химия',
			'Physical basis of information': 'Физические основы получения информации',
			'Physical basis of workflows': 'Физические основы рабочих процессов',
			'Physical fundamentals of electronics (ELF)': 'Физические основы электроники (ФОЭ)',
			'Financial Mathematics': 'Финансовая математика',
			'Functional programming': 'Функциональное программирование',
			'Chemistry': 'Химическая технология',
			'Chemistry': 'Химия',
			'Chemistry and technology of oil and gas': 'Химия и технология нефти и газа',
			'Chemistry of coordination (complex) compounds': 'Химия координационных (комплексных) соединений',
			'Solid State Chemistry': 'Химия твердого тела',
			'Refrigeration and Cryogenic Engineering': 'Холодильная и криогенная техника',
			'Refrigerated food technology': 'Холодильная технология пищевых продуктов',
			'Cold stamping': 'Холодная листовая штамповка',
			'Floriculture': 'Цветоводство',
			'Digital transmission system': 'Цифровые системы передачи',
			'Clothing industry': 'Швейная промышленность',
			'Ecology': 'Экология',
			'Econometrics': 'Эконометрика',
			'Economy Light Industry': 'Экономика легкой промышленности',
			'Engineering Economy': 'Экономика машиностроения',
			'Economy metallurgy': 'Экономика металлургии',
			'Economics of Food Industry': 'Экономика пищевой промышленности',
			'Economics of Agriculture': 'Экономика сельского хозяйства',
			'Construction Economics': 'Экономика строительства',
			'Transport Economics': 'Экономика транспорта',
			'The economy of the chemical industry': 'Экономика химической промышленности',
			'Economics of Energy': 'Экономика энергетики',
			'Electric devices': 'Электрические аппараты',
			'Electrical and thermal engineering measurement': 'Электрические и теплотехнические измерения',
			'Electrical Machines': 'Электрические машины',
			'Electrical systems and networks': 'Электрические системы и сети',
			'Power stations and substations': 'Электрические станции и подстанции',
			'Electricity and Magnetism': 'Электричество и магнетизм',
			'Electromagnetic compatibility in power industry': 'Электромагнитная совместимость в электроэнергетике',
			'Electromagnetic fields and waves': 'Электромагнитные поля и волны',
			'Electromechanical systems': 'Электромеханические системы',
			'Electronics': 'Электроника',
			'Electric drive': 'Электропривод',
			'Electric power supply': 'Электроснабжение',
			'Electrical engineering': 'Электротехника',
			'Electrotechnical materials': 'Электротехнические материалы',
			'Electrotechnological installation': 'Электротехнологические установки',
			'Electrophysical and electrochemical treatments': 'Электрофизические и электрохимические методы обработки',
			'Electrochemistry': 'Электрохимия',
			'Utilities': 'Электроэнергетика',
			'Power systems and complexes': 'Энергетические системы и комплексы',
			'Energy conservation': 'Энергосбережение',
			'Ergonomics': 'Эргономика',
			'Fission and fusion energy': 'Ядерная и термоядерная энергетика',

		'Human Sciences': '',
			'Rescue units': 'Аварийно-спасательные формирования',
			'Psychology': 'Акмеология',
			'Anatomy': 'Анатомия',
			'Anthropology': 'Антропология',
			'Archeology': 'Археология',
			'Architectural Design': 'Архитектурный дизайн',
			'Atheism and freethinking': 'Атеизм и свободомыслие',
			'Life Safety (LS)': 'Безопасность жизнедеятельности (БЖД)',
			'LS in wartime and terrorism': 'БЖД в условиях военного времени и терроризма',
			'LS in Physical Education': 'БЖД в физической культуре',
			'Librarianship and Library Science': 'Библиотечное дело и библиотековедение',
			'Biology': 'Биология',
			'Biomechanics': 'Биомеханика',
			'Biophysics': 'Биофизика',
			'Biochemistry': 'Биохимия',
			'Botany': 'Ботаника',
			'Valeology': 'Валеология',
			'Veterinary science': 'Ветеринария',
			'Genetics': 'Генетика',
			'Geography': 'География',
			'Geoecology': 'Геоэкология',
			'Hygiene and sanepidkontrol': 'Гигиена и санэпидконтроль',
			'Histology': 'Гистология',
			'Civil defense': 'Гражданская оборона',
			'Demography': 'Демография',
			'Design': 'Дизайн',
			'Documentation and record keeping': 'Документоведение и делопроизводство',
			'Journalism': 'Журналистика',
			'Protection in Emergencies': 'Защита в чрезвычайных ситуациях',
			'Zoology': 'Зоология',
			'Publishing': 'Издательское дело',
			'Foreign Languages and Literature': 'Иностранные языки и литература',
			'Art': 'Искусство',
			'History': 'История',
			'Conflict': 'Конфликтология',
			'Jurisprudence': 'Культурология',
			'Linguistics and Languages': 'Лингвистика и языки',
			'Literature': 'Литература',
			'Medicine': 'Медицина',
			'Intercultural Communication': 'Межкультурная коммуникация',
			'Mycology': 'Микология',
			'Microbiology and Biotechnology': 'Микробиология и биотехнология',
			'Museology': 'Музееведение',
			'Musical Art': 'Музыкальное искусство',
			'Oil and gas': 'Нефтегазовое дело',
			'Labor protection': 'Охрана труда',
			'Traffic regulations and road safety': 'ПДД и безопасность дорожного движения',
			'Polygraphy': 'Полиграфия',
			'Political science': 'Политология',
			'Psychodiagnostics and psychological workshop': 'Психодиагностика и психологический практикум',
			'Counselling': 'Психологическое консультирование',
			'Psychology': 'Психология',
			'Psychotherapy': 'Психотерапия',
			'Psychophysiology': 'Психофизиология',
			'Radiation and chemical protection': 'Радиационная и химическая защита',
			'Religious': 'Религиоведение',
			'Restaurant and hotel business': 'Ресторанно-гостиничный бизнес',
			'Rhetoric': 'Риторика',
			'Lighting Design': 'Световой дизайн (светодизайн)',
			'Sculpture': 'Скульптура',
			'Modern foreign media': 'Современные зарубежные СМИ',
			'Sociology': 'Социология',
			'Sport': 'Спорт',
			'Theater': 'Театральное искусство',
			'Toxicology': 'Токсикология',
			'Tourism': 'Туризм',
			'Ukrainian language': 'Украинский язык',
			'Ukrainian Literature': 'Украинская литература',
			'Pharmacology': 'Фармакология',
			'Pharmaceutics': 'Фармацевтика',
			'Physiology': 'Физиология',
			'Physical culture': 'Физическая культура',
			'Philosophy': 'Философия',
			'Cytology': 'Цитология',
			'Ecology': 'Экология',
			'Ethics and aesthetics': 'Этика и эстетика',

	},

};
